Repository ssvlabs/ssv, pull requests merged in 2025-06, with the labels that each got.

#2199 test(protocol/v2/ssv/validator/committee_queue_test.go): verify the functionality of handling messages in a committee queue
  protocol/v2/ssv/validator/committee_queue_test.go
Labels: tests

#2240 [SSV-18] ssvsigner: Insecure Logger Usage May Lead to Information Disclosure
  ssvsigner/cmd/purge-keys/purge-keys.go
Labels: audit

#2285 [SSV-19] ssvsigner: Local Database Is a Single Point of Failure
  ssvsigner/README.md
Labels: audit

#2228 [SSV-3] ssvsigner: Lack of Panic Recovery in Http Handler Wrapper Can Lead to Server Crash
  ssvsigner/server.go
Labels: audit

#2279 [SSV-20] ssvsigner: Server-Side Request Forgery via Web3signer_endpoint Configuration
  ssvsigner/cmd/internal/logger/logger.go
  ssvsigner/cmd/internal/validation/url.go
  ssvsigner/cmd/internal/validation/url_test.go
  ssvsigner/cmd/purge-keys/purge-keys.go
  ssvsigner/cmd/ssv-signer/ssv-signer.go
  ssvsigner/cmd/ssv-signer/ssv-signer_test.go
Labels: audit

#2230 [SSV-5] ssvsigner: High CPU Usage and Potential DoS in the Add Validator Flow Due to Unbounded Share Processing
  ssvsigner/client.go
  ssvsigner/client_test.go
  ssvsigner/server.go
  ssvsigner/server_test.go
Labels: audit

#2236 [SSV-6] ssvsigner: Flawed Error Caching in checkCachePrivkey() Leads to Suppressed Errors and Potential Panic
  ssvsigner/keys/rsa_linux.go
Labels: audit

#2256 [SSV-12] ssvsigner: Local Signer Account Overwrite Risk
  migrations/migration_2_encrypt_shares.go
Labels: audit

#2266 [SSV-2] ssvsigner: SSV Signer Exposes Signing Operations over Unencrypted HTTP or TLS
  ssvsigner/README.md
  ssvsigner/cmd/ssv-signer/ssv-signer.go
  ssvsigner/tls/tls.go
Labels: audit

#2239 [SSV-10] ssvsigner: The Order of Operations in RemoteKeyManager.AddShare() May Lead to Ineffective Local Slashing Protection
  ssvsigner/ekm/remote_key_manager.go
Labels: audit

#2227 [SSV-1, SSV-13] ssvsigner: Fix Potential Race Condition in `RemoteKeyManager` Between Signing Checks and `BumpSlashingProtection()`
  ssvsigner/ekm/remote_key_manager.go
  ssvsigner/ekm/remote_key_manager_test.go
Labels: audit

#2326 chore: migrate coverage badge to Codecov and remove local implementation
  .github/workflows/test-cov.yml
  README.md
  docs/resources/cov-badge.svg
Labels: cleanup

#2289 [S2] ssvsigner: Aes Key Derivation From Rsa Hash Lacks Proper Key Derivation Function
  cli/operator/node.go
  go.mod
  go.sum
  migrations/migration_2_encrypt_shares.go
  migrations/migration_7_derive_signer_key_with_hkdf.go
  migrations/migration_7_derive_signer_key_with_hkdf_test.go
  migrations/migrations.go
  network/peers/connections/mock/mock_storage.go
  operator/storage/storage.go
  ssvsigner/ekm/local_key_manager.go
  ssvsigner/ekm/local_key_manager_test.go
  ssvsigner/ekm/signer_storage.go
  ssvsigner/ekm/signer_storage_test.go
  ssvsigner/go.mod
  ssvsigner/go.sum
  ssvsigner/internal/mocks/mocks.go
  ssvsigner/keys/keys.go
  ssvsigner/keys/keys_test.go
  ssvsigner/keys/rsaencryption/rsa_encryption.go
  ssvsigner/keys/rsaencryption/rsa_encryption_test.go
  ssvsigner/server_test.go
Labels: audit

#2333 UPDATE [SSV-20] ssvsigner: Server-Side Request Forgery via Web3signer_endpoint Configuration
  go.mod
  go.sum
  ssvsigner/cmd/internal/validation/url.go
  ssvsigner/cmd/internal/validation/url_test.go
  ssvsigner/cmd/ssv-signer/ssv-signer_test.go
  ssvsigner/go.mod
  ssvsigner/go.sum
Labels: audit
